apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-first
spec:
  containers:
    - name: nginx-containers
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        limits:
         cpu: "500m"
         memory: "256Mi"
---      
apiVersion: v1
kind: Pod
metadata:
  name: nginx-second
  labels:
    app: sample
spec:
  containers:
    - name: nginx-containers
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        limits:
         cpu: "500m"
         memory: "256Mi"
      