- hosts: all
  become: true

  tasks:
    - name: Install apache2 if Ubuntu
      apt:
        name: apache2
        state: absent
      register: install_result
    
    - name: debug install_result
      debug:
        var: install_result.stdout
  
    - name: start apache2
      service:
        name: apache2
        state: started
      when: install_result.changed