- hosts: all
  become: true
  vars_files:
    - vars.yaml

  tasks:
    - name:
      apt:
        name: "{{ item }}"
        state: absent
      loop: "{{ packages }}"
      when: ansible_facts['os_family'] == "Debian" 