apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
    tier: frontend
  name: rs-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: frontend

  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
    
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx-new
    tier: frontend
  name: rs-nginx-new
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
      tier: frontend

  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
    